### PR TITLE
Adding CLI option

### PR DESCRIPTION
**Pull request by bjesuiter**
This pr adds the option to call this package via cli to be able to use it inside package.json scripts more easily

### CODE REVIEW

**Comment by bjesuiter** [comment]
@simonepri Unfortunately, i'm stuck now. 

The linter (xo) enforced the prefer-destructuring rule for the package.json object in lib.js in line 10 in my branch. 

The problem is, that destructuring is not available prior node 6, so i disabled this preference rule and tried again. 
But now the problem is the xo lib itself, because it uses destructuring in the newest version. 

 The xo lib stands on version * in my package.json so it pulled the latest version, which aparently uses destructuring.

**Which option do you prefer?**

**Comment by simonepri** [comment]
Hi @bjesuiter!
Sorry for the long delay.

I would like to use you code here.

Can you open a new PR with only these changes and close this one? (Without the .gitignore one)
https://github.com/simonepri/project-version/compare/54cef6ec54ef0253a8d830b92152ad9c24616a42?expand=1
And add you to the contributors in the `package.json` as well

**Comment by simonepri** [comment]
@bjesuiter any news?

**Comment by bjesuiter** [comment]
@simonepri Sorry for delayed answer, I was in holidays and was not answering anything ;) 

So, do I understand that correctly that you want all changes you marked with the div link? 
Do you want the .gitignore change added or not? 

Yes, I can add myself to the contributors list :) 

I'll try to make these changes only, but I think, the linter or xo will complain about importing index.js via relative path. 
Maybe we need to work out a solution for that.

**Comment by simonepri** [comment]
No problem!
Thank you for the time you spent contributing!

Check the PR for the lint error fix

**Comment by bjesuiter** [comment]
@simonepri It's my pleasure :) It was very fun making my first contribution to an open source project! 👍

**Pull request closed without merging**
